### ISSUE TITLE
Layout in Popover gets 0 size

### ISSUE THREAD

**Issue by VinceBurn** [tevelee/SwiftUI-Flow#16]
I've created a View to be use in a pop over.
I've configure the layout like this:
```
HFlow(
    alignment: .center,
    itemSpacing: 12,
    rowSpacing: nil,
    justification: nil,
    distributeItemsEvenly: true
)
```

And used it like this:
```
.popover(isPresented: $isSelectAmountPopoverActive, content: {
    ChipSelectorView()
        .padding()
        .presentationCompactAdaptation(.popover)
})
```

The size that the popover is taking is only the size of the padding.

Here is a screenshot where I we can see the view inserted in a normal view (behaving correctly) and the view in the popover.

<img width="593" alt="LayoutInPopOver" src="https://github.com/tevelee/SwiftUI-Flow/assets/5777036/71cdd583-9630-407b-af58-62aa271b2d21">

I can manage to have something kind of working if I add a `.frame(width: 300)` or  `.frame(minWidth: 300)`, but I'm trying to avoid putting a specific number as the project is for iPhone, iPad and MacOS.

Any idea if this would be due to how popover determine their size or if it would be a configuration error?

**Comment by tevelee** [comment]
Thank you for reporting this issue, @VinceBurn. It demonstrated a bug in the layout code.

The layout engine used [ProposedViewSize.replacingUnspecifiedDimensions(by:)](https://developer.apple.com/documentation/swiftui/proposedviewsize/replacingunspecifieddimensions(by:)) API that turns out to be using a default value of 10x10. This might be the reason your screenshot shows the small square sized popover. I was unaware of this default value and [fixed](https://github.com/tevelee/SwiftUI-Flow/commit/733c317daaf900d1bb513bcdc70f463ccb9180ef) this by providing a more sensible default value in the latest `1.7.0` release. Please take a look.

Answering the second part of your question, I think using the `.fixedSize()` modifier is a great way to avoid artificial magic numbers and let the view size itself accordingly.

```swift
import Flow
import SwiftUI

@main
struct ExampleApp: App {
    var body: some Scene {
        WindowGroup {
            Container()
        }
    }
}

struct Container: View {
    @State private var popover = false

    var body: some View {
        Button("Popover") {
            popover = true
        }
        .popover(isPresented: $popover) {
            HFlow(itemSpacing: 12) {
                Chip(value: 0.5, color: .brown)
                Chip(value: 1, color: .gray)
                Chip(value: 2, color: .purple)
                Chip(value: 5, color: .red)
                Chip(value: 25, color: .green)
                Chip(value: 100, color: .black)
            }
            .fixedSize()
        }
        .frame(width: 400, height: 300)
    }
}

struct Chip: View {
    let value: Double
    let color: Color

    var body: some View {
        Circle()
            .fill(color)
            .overlay {
                Text(value, format: .number.precision(.fractionLength(0...1)))
                    .foregroundStyle(.white)
            }
            .frame(width: 50, height: 50)
    }
}

#Preview {
    Container()
}
```

With the fix now it looks like this:

![image](https://github.com/tevelee/SwiftUI-Flow/assets/443078/afcc1912-b965-4902-b612-ac17f6010ca0)

**Comment by VinceBurn** [comment]
Thanks, it helps for the macOS, but there is still issues on iOS and the fixedSize appears to be a band-aid.

If I use the same code as your response but with more chips I'm getting the following:
<img width="943" alt="oniPadFixedSize" src="https://github.com/tevelee/SwiftUI-Flow/assets/5777036/8b619310-e047-4489-b020-43273198ce57">

If I remove the fixedSize I would get this:

<img width="945" alt="oniPadNOTFixedSize" src="https://github.com/tevelee/SwiftUI-Flow/assets/5777036/b738ba2b-13d8-4289-9389-f93c3f623272">

The first one (with fixed size) looks like it fixes the Layout to a single row as we see that the popover doesn't go on multiple line.

The second one (without fixed size) appear to have layout the grid, but the popover takes a "view port" for a single row. In the popover dismiss animation I can see other part of the grid.

For fun I have recreated a very basic Horizontal Flow Layout to explore how the protocol works. I've notice that the systems call the layout protocol a lot with different proposal to try do define values. I have the feeling that there might be a bug / challenge in Appel's implementation. As the Layout was returning different size for different proposal and it appears that the system is taking valued from different proposal responses. It is really weird.
