### ISSUE TITLE
how to align HFlow to the left?

### ISSUE THREAD

**Issue by halpz** [tevelee/SwiftUI-Flow#5]
how can I arrange a HFlow to start from the left and not have items just centred  in the middle when there are not enough items to fill a row?

the alignment property seems to only apply to the vertical aspect of items

**Comment by halpz** [comment]
and also the HFlow component doesn't seem to fill the available area by default

**Comment by tevelee** [comment]
Hi @halpz, 

Thanks for the question! HFlow follows the same philosophy as HStack does (according to the SwiftUI layout engine), it fits around the content. The view gets proposed the full screen size, it measures its children and reports the smallest viable dimensions.

> how can I arrange a HFlow to start from the left and not have items just centred in the middle when there are not enough items to fill a row?

In order to achieve the desired effect, you can use a `frame` modifier with a leading alignment like so:
```swift
HFlow {
    ForEach(1...10, id: \.self) { _ in
        Color.orange.frame(width: 20, height: 20)
    }
}
.frame(maxWidth: .infinity, alignment: .leading)
```

This arrangement is not HFlow specific, but a general layout philosophy of SwiftUI. You can do this with every SwiftUI view, such as HStack and Text. Please take a look at this excellent blogpost to cover the details: https://sarunw.com/posts/how-to-make-swiftui-view-fill-container-width-and-height/

By the way, HStack also centers their content by default.

> the alignment property seems to only apply to the vertical aspect of items

HStack [also](https://developer.apple.com/documentation/swiftui/hstack/init(alignment:spacing:content:)) provides vertical alignment properties in its initializer, because that's what is makes sense for the layout. Otherwise, with variable height views there would be no way to customize where the child views should be places on the vertical axis. Hence, this belongs to the layout container to decide.

> and also the HFlow component doesn't seem to fill the available area by default

Yeah, same as HStack.

**Comment by Kinark** [comment]
@tevelee How can I make it centered again? Now it seems to default to leading

**Comment by tevelee** [comment]
Can you please provide a sample code where you experienced broken alignment?

**Comment by tevelee** [comment]
Also check out 2.5.0 where you have the option to individually control both horizontal and vertical alignment at the same time.
